### ISSUE TITLE
Execute permission lacking

### ISSUE THREAD

**Issue by clcii** [OCSInventory-NG/OCSInventory-Docker-Stack#11]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Windows 10

### Docker informations
Docker compose version : 1.25.5
Docker version : 19.03.8

### Problem's description
Running docker-compose up -d

I receive : 
ocsinventory-db is up-to-date
Starting ocsinventory-server ... error                                                                                  
ERROR: for ocsinventory-server  Cannot start service web: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/docker-entrypoint.sh\": permission denied": unknown

docker-entrypoint.sh does not seem to have executable privilidges

docker-compose.yml

 ```
version: '3'
services :
  web :
    image : ocsinventory/ocsinventory-docker-image:latest
    container_name : ocsinventory-server
    environment :
      OCS_DBNAME : ocsweb
      OCS_DBSERVER_READ : ocsinventory-db
      OCS_DBSERVER_WRITE : ocsinventory-db
      OCS_DBUSER : ocs
      OCS_DBPASS : ocs
    volumes :
      - ocsdownload:/usr/share/ocsinventory-reports/ocsreports/download/
      - ocssrv:/etc/ocsinventory-reports/
      - ocslib:/var/lib/ocsinventory-reports/
    links :
      - db
    ports :
      - 80:80
      - 443:443

  db :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocs
      MYSQL_DATABASE : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql
    ports :
      - 3306:3306

volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
  ocslib:
    driver: local
  ocsdownload:
    driver: local






```

**Comment by gillesdubois** [comment]
Hi,

This repository is not used anymore, please post on the image repository.

Regards,
Gilles Dubois.
