### ISSUE TITLE
what is the default login account and password ?

### ISSUE THREAD

**Issue by changchichung** [OCSInventory-NG/OCSInventory-Docker-Stack#6]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system :  ubuntu 18.04

### Docker informations
Docker compose version : 1.22 .0
Docker version :  18.06.1-ce

### Problem's description
I clone the repo , and edit docker-compose.yml for needs , then run docker using docker-compose up -d , and open http://docker_host:expose_port/ocsreports , after update , then open http://docker_host:expose_port/ocsreports/index.php?first
But what is the default login account and password ?
I find no related info in README.md / setup.sh / docker-compose.yml .

**Comment by loranger** [comment]
I had the same problem. If others arrive here too, the credentials are [the default ones](https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/#configuring-management-server) (at the very bottom of the page).
