### ISSUE TITLE
 How can I update OCS Inventory-NG server ?

### ISSUE THREAD

**Issue by AyoubAD** [OCSInventory-NG/OCSInventory-Docker-Stack#9]
### General informations
Docker host's operating system : 

### Docker informations
Docker compose version :
Docker version : 

### Problem's description
*Describe your problem here*

**Comment by gillesdubois** [comment]
Hi,

Our Docker image has been reworked completly.
2.6 / nightly / dev tags are now available.

A complete documentation is available on wiki.
Compose files are now located on the image repository and not on this one anymore.

Regards,
Gilles Dubois.
